export const GET_ORDERS_REQUEST="GET_ORDERS_REQUEST"
export const GET_ORDERS_SUCCESS="GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAILURE="GET_ORDERS_FAILURE"

export const CONFIRM_ORDER_REQUEST="CONFIRM_ORDER_REQUEST"
export const CONFIRM_ORDER_SUCCESS="CONFIRM_ORDER_SUCCESS"
export const CONFIRM_ORDER_FAILURE="CONFIRM_ORDER_FAILURE"

export const SHIPPED_ORDER_REQUEST="SHIPPED_ORDER_REQUEST"
export const SHIPPED_ORDER_SUCCESS="SHIPPED_ORDER_SUCCESS"
export const SHIPPED_ORDER_FAILURE="SHIPPED_ORDER_FAILURE"

export const CANCEL_ORDER_REQUEST="CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_SUCCESS="CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAILURE="CANCEL_ORDER_FAILURE"

export const DELIVERED_ORDER_REQUEST="DELIVERED_ORDER_REQUEST"
export const DELIVERED_ORDER_SUCCESS="DELIVERED_ORDER_SUCCESS"
export const DELIVERED_ORDER_FAILURE="DELIVERED_ORDER_FAILURE"

export const DELETE_ORDER_REQUEST="DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS="DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILURE="DELETE_ORDER_FAILURE"