export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_ORDER_FAILURE";
